### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by n0mar** [Aeneon/TDK#1]
**Hey!**

I have some icon requests, and some that are already in the "Unknown" folder too, such as:

App: Imgur
Bundle ID: `imgurmobile`
Icon: [Icon](https://github.com/Aeneon/TDK/blob/master/Icons/Community%20(%20MacThemes%20)/Unknown%20Apps/w6Dg6.png)

App: Minigore
Bundle ID: `com.chillingo.minigore` & `ms.games.minigore2` (although this one has a completely different icon, I'm sure you could just use the same icon for both games)
Icon: [Icon](https://github.com/Aeneon/TDK/blob/master/Icons/Community%20(%20MacThemes%20)/Unknown%20Apps/75831591.png)

---

### My Requests

App: Workflow
Bundle ID: `is.workflow.my.app`
Icon:
<img src="http://is1.mzstatic.com/image/thumb/Purple111/v4/19/ce/ee/19ceeeb1-fb84-2e82-2474-421fdeb936fc/source/512x512bb.jpg" width="48">

App: RecordBird
Bundle ID: `com.recordbird.recordbird`
Icon:
<img src="http://is4.mzstatic.com/image/thumb/Purple122/v4/3c/38/e7/3c38e736-3d91-749d-30ad-71d73ab2e820/source/512x512bb.jpg" width="48">

App: GuitarToolkit
Bundle ID: `com.agilepartners.GuitarToolkit `
Icon:
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/2b/0e/81/2b0e8120-fc52-b868-9afa-d0ac09a91729/source/512x512bb.jpg" width="48">

App: Pocket Weather Australia
Bundle ID: `au.com.shiftyjelly.pocketweatherau.three `
Icon:
<img src="http://is4.mzstatic.com/image/thumb/Purple111/v4/b2/25/7b/b2257bce-00f2-0b61-32b4-9b2d2b9978f4/source/512x512bb.jpg" width="48">

App: Ultralight
Bundle ID: `com.ultralightapp.Ultralight `
Icon:
<img src="http://is4.mzstatic.com/image/thumb/Purple62/v4/8c/5a/55/8c5a5554-0b70-7c03-184d-9aa08eda30ad/source/512x512bb.jpg" width="48">

App: Logic Remote
Bundle ID: `com.apple.musicapps.remote `
Icon:
<img src="http://is2.mzstatic.com/image/thumb/Purple62/v4/f8/2a/cc/f82acc09-3311-a4d6-0fd0-ca2f80b5041f/source/512x512bb.jpg" width="48">

App: Buffer
Bundle ID: `com.buffer.buffer `
Icon:
<img src="http://is1.mzstatic.com/image/thumb/Purple122/v4/9b/d4/2c/9bd42c8e-3cfa-c688-6cb2-6dcbba459853/source/512x512bb.jpg" width="48">

App: Globo
Bundle ID: `com.marco.Globo `
Icon:
<img src="http://is1.mzstatic.com/image/thumb/Purple71/v4/e2/fc/c7/e2fcc784-c38f-a745-9269-410add3d75f7/source/512x512bb.jpg" width="48">

App: IFTTT
Bundle ID: `com.ifttt.ifttt`
Icon:
<img src="http://is5.mzstatic.com/image/thumb/Purple122/v4/d7/79/09/d779092e-fd62-2f1b-d2fd-410f220f331c/source/512x512bb.jpg" width="48">

The icon provided is the new/current icon, which is really not that good, and I think it would be better to use the old/previous icon instead ([here](http://www.15minutemondays.com/wp-content/uploads/2014/05/ifttt_icon.jpg))

**Comment by Aeneon** [comment]
I'll add them in the next Update 😊 …
